---

- name: "VLANConfiguration: Creating the description with job id {{ tower_job_id }}"
  block:
    - set_fact:
        ansible_tower_job_id: "{{ TOWER_PREFIX }}_{{ tower_job_id }}"

    - name: "Updating the description"
      set_fact:
        updated_desc: "{{ item.description }}::{{ ansible_tower_job_id }}"
  when: tower_job_id is defined

#For some reasons not able to add the description using ios_vlans module. Hence adding via ios_config
# we shall be updating the description only when the description is not empty. If empty, then it throws
#exception of type "incomplete command"
- set_fact:
    default_description: "{{ item.description | default(description) }}"

- name: "VLANConfiguration: Adding description to vlan {{ item.vlan_id }}"
  ios_config:
   lines:
      - "description {{ updated_desc | default(default_description) }}"
   parents: "interface vlan {{ item.vlan_id }} "
  when: updated_desc is defined or default_description|trim != ""

#interface Vlan4
 #description SVI ops_pc
 #vrf forwarding vrf-opscc
 #ip address 10.152.120.222 255.255.255.224
 #no ip redirects
 #no ip unreachables
 #no ip proxy-arp
 #ipv6 address 2001:df3:bf80:4285:10:152:120:222/64
 #ipv6 enable
 #ipv6 nd prefix 2001:df3:bf80:4285::/64 2592000 604800 no-autoconfig
 #ipv6 nd managed-config-flag
 #ipv6 nd other-config-flag
 #ipv6 nd router-preference High
 #no ipv6 redirects
 #ospfv3 1 ipv4 area 1
 #ospfv3 1 ipv6 area 1
 #no shut
- name: "VLANConfiguration: Adding SVI ipv4  to vlans"
  block:
    #ip_util module will validate the ipaddress and fetch useful information like network, netmask, hostmask etc
   - ip_util:
       ip_address: "{{ item.ipv4addr }}"
       type: "ipv4"

   - name: "VlanSVIConfiguration: Validating the ip mask"
     fail:
      msg: "Either ip mask is not defined or empty"
     when: item.ip_mask is not defined or item.ip_mask|trim==""

   - name: "VlanSVIConfiguration : Setting the SVI ipv4 {{ item.ipv4addr }} to vlan id {{ item.name }} "
     ios_config:
      lines:
        - "ip address {{ item.ipv4addr }} {{ item.ip_mask }}"
        - "no ip redirects"
        - "no ip unreachables"
        - "no ip proxy-arp"
        - "ospfv3 1 ipv4 area 1"
        - "no shut"
      parents: "interface vlan {{ item.vlan_id }} "
  when: item.ipv4addr is defined

- name: "VLANConfiguration: Adding SVI ipv6  vlans"
  block:
    #ip_util module will validate the ipaddress and fetch useful information like network, netmask, hostmask etc
   - ip_util:
      ip_address: "{{ item.ipv6addr }}"
      type: "ipv6"
     register: ip_details


   - name: "VlanSVIConfiguration : Setting the SVI ipv6  {{ item.ipv6addr }}to vlan id {{ item.name }} "
     ios_config:
      lines:
        - "ipv6 address  {{ item.ipv6addr }} "
        - "ipv6 enable"
        - "ipv6 nd prefix {{ ip_details.network }} 2592000 604800 no-autoconfig"
        - "ipv6 nd managed-config-flag"
        - "ipv6 nd other-config-flag"
        - "ipv6 nd router-preference High"
        - "no ipv6 redirects"
        - "ospfv3 1 ipv6 area 1"
        - "no shut"
      parents: "interface vlan {{ item.vlan_id }} "
  when: item.ipv6addr is defined

- include_tasks: verify_logical_layer3_configuration.yml
