---

- include: "../../common/tasks/gather_facts.yml"
  vars:
    task_name: "VLANConfigurationPrelim"
    resources: ["vlans"]

- name: "Dumping the results"
  debug:
   var: result

- name: "Building vlan id list"
  set_fact:
    #convert the vlan_id to integer while putting into the list
   vlan_id_list: "{{ vlan_id_list }} + [ '{{ item.vlan_id|int }}' ]"
  with_items: "{{ result.ansible_facts.ansible_network_resources.vlans }}"

- name: "Dumping the interface list"
  debug:
   msg: "{{ vlan_id_list }}"

