---
- name: "VLANConfiguration: Adding SVI to vlans"
  block:
   - name: "VlanSVIConfiguration: Validating the ip addres"
     fail:
      msg: "ip address cannot be empty"
     when: item.ipv4addr|trim==""

   - name: "VlanSVIConfiguration: Validating the ip mask"
     fail:
      msg: "Either ip mask is not defined or empty"
     when: item.ip_mask is not defined or item.ip_mask|trim==""

   - name: "VlanSVIConfiguration : Setting the SVI to vlan id {{ item.name }} "
     ios_config:
      lines:
        - "ip address {{ item.ipv4addr }} {{ item.ip_mask }}"
      parents: "interface {{ item.name }} "
  when: item.ipv4addr is defined