---
- name: "SwitchBaseACLCreation: Generating acl commands"
  set_fact:
    acl_commands: "{{ lookup('template', './acl_creation_commands.j2') }}"

- debug:
     var: acl_commands

- name: "SwitchBaseACLCreation: Executing acl creation commands"
  ios_command:
    commands: "{{ acl_commands }}"
  register: result

- name: "SwitchBaseACLPostCreationVerification: Executing the search in the device"
  ios_command:
    commands:
     - "show access-lists  {{ acl_num }} "
  register: standard_list

- debug:
   msg: "ACL list configured for {{ acl_num }} is \n {{ standard_list.stdout[0] }}"