---
- set_fact:
   combined_acl_list: []
   cacheable: True

- name: "Fetching acl information"
  include_tasks: fetch_acl_checks.yml
  loop: "{{ acl_list }}"

- debug:
   var: combined_acl_list

# now time to generate report

- include_role: report
  vars:
    - report_template_name: "acl_report.j2"
    - title: "ACL Job Status report"

