---
- set_fact:
   combined_acl_list: []
   cacheable: True

- name: "Fetching acl information"
  include_tasks: fetch_acl_checks.yml
  loop: "{{ acl_list }}"

- debug:
   var: combined_acl_list

- debug:
    msg: "{{ item }}"
  loop: "{{ lookup('inventory_hostnames', 'all', wantlist=True) }}"

- name: generating dir name by the name of date
  set_fact:
      curr_date: "{{lookup('pipe','date \"+%Y-%m-%d \"')}}"
- name: creating UUID
  generate_uuid:
  register: uuid
- name: print uuid
  debug:
    var: uuid

- name: Create reports/ folder to save reports
  run_once: yes
  local_action:
    module: file
    path: "./reports/{{ curr_date }}/{{ uuid.uuid }}"
    state: directory

#Setting the facts for generating the HTML report
- set_fact:
    title: "ACL Job Status Report"
    tower_id: "NA."
    curr_date: "{{lookup('pipe','date \"+%Y-%m-%d %H:%M\"')}}"

- name: Generate job report
  delegate_to: 127.0.0.1
  run_once: yes
  template:
   src: "./templates/acl_report.j2"
   dest: "reports/{{ curr_date }}/{{ uuid.uuid }}/report.html"

- name: Generate job report
  delegate_to: 127.0.0.1
  run_once: yes
  copy:
   src: "./templates/psa_banner.jpeg"
   dest: "reports/{{ curr_date }}/{{ uuid.uuid }}"

- name: zipping adding password to reports
  shell: zip --password pass123 reports/{{ curr_date }}/{{ uuid.uuid }}/{{ uuid.uuid }}.zip reports/{{ curr_date }}/{{ uuid.uuid }}/*

- name: sending mail
  mail:
    subject: Ansible-report
    body: Hello, this is ios acl report ;-)
    to: Prashanth <pras@ansible-srv>
    attach: "reports/{{ curr_date }}/{{ uuid.uuid }}/{{ uuid.uuid }}.zip"
  delegate_to: localhost
  #

