---
- set_fact:
   combined_acl_list: []
   cacheable: True

- name: "Fetching acl information"
  include_tasks: fetch_acl_checks.yml
  loop: "{{ acl_list }}"

- debug:
   var: combined_acl_list

- debug:
    msg: "{{ item }}"
  loop: "{{ lookup('inventory_hostnames', 'all', wantlist=True) }}"

- name: Create reports/ folder to save reports
  run_once: yes
  local_action:
    module: file
    path: "./reports"
    state: directory

#Setting the facts for generating the HTML report
- set_fact:
    title: "ACL Job Status Report"
    tower_id: "NA."
    curr_date: "{{lookup('pipe','date \"+%Y-%m-%d %H:%M\"')}}"

- name: Generate job report
  delegate_to: 127.0.0.1
  run_once: yes
  template:
   src: "./templates/acl_report.j2"
   dest: "reports/report.html"

- name: Generate job report
  delegate_to: 127.0.0.1
  run_once: yes
  copy:
   src: "./templates/psa_banner.jpeg"
   dest: "reports"


- name: creating unique ID
  set_fact:
      unique_id: "{{lookup('community.general.random_string')}}"
      cacheable: True
- name: zipping adding password to reports
  shell: zip --password pass123 {{ unique_id }}.zip reports/*

- name: sending mail
  mail:
    subject: Ansible-report
    body: Hello, this is ios acl report ;-)
    to: Prashanth <pras@ansible-srv>
    attach: "{{ unique_id }}.zip"
  delegate_to: localhost
  #

