---
- name: "PhysicalLayer3Configuration PostCheck: Verification"
  ios_command:
     commands: "show run interface {{ item.name }}"
  register: actual_result

- name: "Dumping actual configuration for physical layer3 configuration {{ item.name }}"
  debug:
    var: actual_result

- name: "Extracting entries"
  extract:
   regex: '^\s(.*)'
   lines: "{{ actual_result.stdout[0] }}"
  register: layer3_configurations

- debug:
    var: layer3_configurations

- set_fact:
    verified_list: []

- set_fact:
    verified_list: "{{ verified_list }} + [  '{{ layer3_entry }}' ] "
  when:  layer3_entry not in layer3_configurations.result
  loop: "{{ expected_physical_layer3_options }}"
  loop_control:
    loop_var: layer3_entry

- debug:
    var: verified_list

- fail:
    msg: "Not all configurations are applied. Configuration that are not applied are {{ verified_list }}"
  when: verified_list| length>0

- debug:
    msg: "Physical layer3 interface is successfully configured."