---
ansible_network_os: ios
ansible_connection: network_cli
supported_config_types: ["SWITCH_PORT_CONFIGURATION","VLAN_CONFIGURATION","AUDIT"]
crud_operations: ["CREATE","UPDATE"]
non_crud_operations: ["AUDIT"]
supported_operation_types: "{{ crud_operations + non_crud_operations }}"
description:
TOWER_PREFIX: TID