---
- name: "SwitchPortConfigurationPrelim: Prelim operation"
  debug:
    msg: "Executing prelim operations for switch port configuration"

- name: "SwitchPortConfigurationPrelim: Validating if switch port config is provided or not"
  fail:
   msg: "Switch port configuration is not provided"
  when: config is not defined

- include: "../../common/tasks/gather_facts.yml"
  vars:
    task_name: "SwitchPortConfigurationPrelim"
    resources: ["interfaces","vlans"]

- name: "SwitchPortConfigurationPrelim: Dumping the results"
  debug:
   var: result

- name: "SwitchPortConfigurationPrelim: Building interface list"
  set_fact:
   interface_list: "{{ interface_list }} + [ '{{ item.name }}' ]"
  with_items: "{{ result.ansible_facts.ansible_network_resources.interfaces }}"
  no_log: True

- name: "SwitchPortConfigurationPrelim: Dumping the interface list"
  debug:
   msg: "{{ interface_list }}"

- name: "SwitchPortConfigurationPrelim: Building vlan id list"
  set_fact:
    #convert the vlan_id to integer while putting into the list
   vlan_id_list: "{{ vlan_id_list }} + [ '{{ item.vlan_id|int }}' ]"
  with_items: "{{ result.ansible_facts.ansible_network_resources.vlans }}"
  no_log: True

- name: "SwitchPortConfigurationPrelim: Dumping the interface list"
  debug:
   msg: "{{ vlan_id_list }}"

