---
- name: "SwitchPortConfiguration: Creation operation"
  debug:
    msg: "Executing create operation for switch port configuration"

- name: "SwitchPortConfiguration: Ensuring config data conforms to the schema"
  ansible.utils.validate:
   data: "{{ config }}"
   criteria: "{{ lookup('ansible.builtin.file', './l2_interface_schema_creation.json')}}"
   engine: ansible.utils.jsonschema

- name: "SwitchPortConfiguration: Ensuring interfaces names given already exist."
  fail:
   msg: "Interface name {{ item.name }} doesn't exist"
  when: item.name not in interface_list
  with_items: "{{ config }}"

- name: "SwitchPortConfiguration: Validating the vlan id  when type is access"
  fail:
    msg: "Vlan id {{ item.access['vlan'] }} doesn't exist"
  when: item.access is defined and item.access['vlan']|string not in vlan_id_list
  with_items: "{{ config }}"

- name: "SwitchPortConfiguration: Pushing the configuration"
  ios_l2_interfaces:
    config: "{{ config }}"
    state: "merged"
  register: result

- name: "SwitchPortConfiguration: Dumping the configuration result"
  debug:
   var: result


