#DeVnet_TESTsw#install add file bootflash:cat9k_iosxe.17.03.03.SPA.bin activate commit
#install_add_activate_commit: START Wed Sep 29 04:22:17 UTC 2021

#System configuration has been modified.
#Press Yes(y) to save the configuration and proceed.
#Press No(n) for proceeding without saving the configuration.
#Press Quit(q) to exit, you may save configuration and re-enter the command. [y/n/q]y<--- this is the user input

---
#RTo solve the issue commadn not authorized
## conf t
# aaa authorization commands 0 default local
#aaa authorization commands 1 default local
#aaa authorization commands 15 default local
- name: "Upgrade: Save running config"
  ios_config:
     save_when: always

- name: "Upgrade: Starting to upgrade"
  ios_upgrade:
    command: 'install add file bootflash:{{ upgraded_fw_name }} activate commit'
  register: pre_reload_op

- name: "Upgrade:Dumping the output of device before reload"
  debug:
   var: pre_reload_op

- name: "Upgrade: Waiting for the device to come back online"
  wait_for:
     host: "{{ inventory_hostname }}"
     port: 22
     delay: 90
     timeout: 900
  delegate_to: localhost

