---

- name: "CommonValidations: Ensuring type variable is defined"
  fail:
    msg: "Either the usecase type is undefined or it is empty"
  when: operation_type is not defined or operation_type==""

- name: "CommonValidations: Ensure valid type values are provided"
  fail:
    msg: "Invalid usecase type {{ type }} provided. Valid usecase types are {{ supported_types }}"
  when: operation_type|upper not in supported_types
