---
- name: "CheckCompliance: Check the compliance"
  ios_config:
    diff_against: intended
    intended_config: "{{ lookup('file', 'master.cfg') }}"
  register: diff_result
  changed_when: false

- debug:
    var: diff_result.diff.after