---

- include_tasks: check_compliance_entity.yml
  loop: "{{ entity_list }}"

- fail:
    msg: "The compliane check has failed. The failures are {{ combined_error }}"
  when: combined_error.keys()|length>0

- debug:
    msg: "No deviation found."
