---
- name: "CheckCompliance: Check the {{ item.entity_name }} compliance"
  ios_command:
     commands: "show run | {{ item.grep_cmd }}"
  register: actual_result

# THis result will have new line, you need to create the list of results and then iterate through
- set_fact:
   actual_result_list: "{{ actual_result.stdout_lines[0] }}"
- debug:
    var: actual_result_list
- set_fact:
    error_list: []
- set_fact:
    error_list: "{{ error_list }} + [  '{{ item }}' ] "
  when:  item not in actual_result_list
  loop: "{{ item.expected_result }}"

- set_fact:
   combined_error: "{{
                     combined_error | combine(
                     {
                       item.entity_name: error_list
                     })
                 }}"
   cacheable: yes
  when: error_list|length>0
- debug:
    var: combined_error
